version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
